### ISSUE TITLE
map does not change

### ISSUE THREAD

**Issue by mrdiega** [ismail0234/Benson-Map-Crash-Fixer#1]
There are times when map timer ends at the same time as the start of the round. In this case, the map is restarted to the same one, and at the same time it is impossible to play on it, since it is supposedly already ended

The plugin is installed on a server with the Multi-1v1 mod
SourceMod Version: 1.10.0.6502
Metamod version: 1.11.0-dev+1144

**Comment by sashajov** [comment]
Can you try this command?

`mp_match_end_changelevel 1`

**Comment by mrdiega** [comment]
I already have this command

**Comment by ismail0234** [comment]
@mrdiega Can you check it from the game by typing 

!cvar mp_match_end_changelevel

**Comment by mrdiega** [comment]
`mp_match_end_changelevel`
`"mp_match_end_changelevel" = "1" ( def. "0" ) min. 0.000000 max. 1.000000 game replicated - At the end of the match, perform a changelevel even if next map is the same`

**Comment by ismail0234** [comment]
> `mp_match_end_changelevel`
> `"mp_match_end_changelevel" = "1" ( def. "0" ) min. 0.000000 max. 1.000000 game replicated - At the end of the match, perform a changelevel even if next map is the same`


can you try these settings? and check that it changes in the game.

mp_match_end_changelevel 1
mp_endmatch_votenextmap 0
mp_endmatch_votenextleveltime 15
mp_match_end_restart 0
